execute pathogen#infect()
set expandtab
set background=dark
:map <leader>gf :e <cfile><cr>
set paste
set ruler
set tags=tags;
set splitright
set matchpairs+=<:>

" Russian keyboard.
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0
highlight lCursor guifg=NONE guibg=Cyan

" Spell check accepting Russian yo.
set spell spelllang=ru_yo,en_us
set nospell

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
    syntax on
    set hlsearch
endif

" This only tracks changes done using vim.
augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }

" Reload vimrc.
nmap  <leader>rc :so $MYVIMRC<CR>
" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>
" <C-t> for :tag .
nnoremap <silent> <C-t> :tag |
" Remove spaces before newlines.
nmap <leader>rs :%s/\s\+$//<CR>
" Replace sequences of 8 spaces with tabs (dosn't work. TODO: write a function)
nmap <leader>tt <Esc>:'<,'>s;[ ]\{8,8\};\t;g<CR>

" Go to prev/next buffer.
nnoremap <silent> '] :bnext<CR>
nnoremap <silent> ]' :bprev<CR>

" Write file to disk if there were changes.
nnoremap zz :update<CR>

" doesn't work...
imap <C-F> <Esc>

set shiftwidth=2
set softtabstop=2
set textwidth=79
set fo-=ro fo+=cql
set hidden	    " Possibility to have more than one unsaved buffer.
set wildmenu	    " Great command-line completion, use '<Tab>' to
		    " move around and '<CR>' to validate.

" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1
" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1
" " Align line-wise comment delimiters flush left instead of following code indentation
" let g:NERDDefaultAlign = 'left'
" Allow commenting and inverting empty lines (useful when commenting a region)
let g:NERDCommentEmptyLines = 1
" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1
let g:NERD_use_ada_with_spaces = 1

hi Comment	guifg=#007f7f cterm=none
hi Constant	cterm=none
hi Special	cterm=none
hi Type		cterm=none
hi Statement	cterm=none
hi PreProc	cterm=none
