execute pathogen#infect()
set hlsearch
set expandtab
set background=dark
:map <leader>gf :e <cfile><cr>
set paste
set ruler
set tags=tags;
set splitright
" This only tracks changes done using vim.
augroup reload_vimrc " {
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END " }
" Reload vimrc.
nmap  <leader>rc :so $MYVIMRC<CR>
" <Ctrl-l> redraws the screen and removes any search highlighting.
nnoremap <silent> <C-l> :nohl<CR><C-l>
" Remove spaces before newlines.
nmap <leader>rs :%s/\s\+$//<CR>
" Replace sequences of 8 spaces with tabs in the entire file.
nmap <leader>tt :%s;[ ]\{8,8\};\t;g<CR>

" Go to prev/next buffer.
nnoremap <silent> '] :bnext<CR>
nnoremap <silent> ]' :bprev<CR>

" Write file to disk if there were changes.
nnoremap zz :update<CR>

" doesn't work...
imap <C-F> <Esc>

set shiftwidth=2
set softtabstop=2
set textwidth=79
set fo-=ro fo+=cql
set hidden	    " Possibility to have more than one unsaved buffer.
set wildmenu	    " Great command-line completion, use '<Tab>' to
		    " move around and '<CR>' to validate.
