#!/bin/bash

if [ "$#" = 0 ]; then
    {
        echo "usage: $0 [-w wrapper] <C code...>"
        echo "CFLAGS environment variable is honored."
    } >&2
    exit 1
fi

if [ "$1" = -w ]; then
    wrapper="$2"
    shift 2
fi

f=$(mktemp -d -t gccrun.XXXXXXXX) || exit 1
cat > "$f/command.c" << EOF
#define _GNU_SOURCE
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mman.h>
#include <sys/ptrace.h>
#include <sys/syscall.h>
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <sched.h>
#include <setjmp.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <linux/prctl.h>  /* Definition of PR_* constants */
#include <sys/prctl.h>

int
main(int argc, char *argv[], char *envp[])
{
        (void)argc;
        (void)argv;
        (void)envp;
	$1;
	return 0;
}
EOF
shift
# shellcheck disable=SC2086
if ! gcc $CFLAGS -o "$f/command" "$f/command.c" "$@"; then
    exit 1
fi
if [ -n "$wrapper" ]; then
    $wrapper "$f/command"
else
    "$f/command"
fi
r=$?
rm -r "$f"
exit $r
