#!/bin/bash -

die()
{
    echo "$*" >&2
    exit 1
}

options=(-yy -f -s 1024)
dump_options=false
record_env=true
trace="-e trace=execve,vfork"
wrapper_opts_ended=false
prog_arguments=()
while [ "$#" -ne 0 ]
do
  $wrapper_opts_ended && break
  case "$1" in
      -d|--dump*)
          dump_options=true
          ;;
    --noenv)
      record_env=false
      ;;
    --full)
      # TODO: I think %file should include chdir (check).
      trace="$trace,%file,%desc,chdir,%%stat,%network,%ipc,%process"
      ;;
    --all)
      trace="-e trace=all"
      ;;
    --)
      wrapper_opts_ended=true
      ;;
    *)
      die "$0: unknown option $1"
      ;;
  esac
  shift
done

$record_env && options+=(-v)
options+=("$trace")

if $dump_options; then
    echo "strace ${options[*]}"
    exit
fi

! $wrapper_opts_ended && die "$0: end wrapper's options with a --"

while [ "$#" -ne 0 ]
do
  prog_arguments+=("$1")
  shift
done

logname="/tmp/strace-$(ls /tmp/strace-* 2>/dev/null | wc -l)"
options+=(-o "$logname" "$@")

strace "${options[@]}" "${prog_arguments[@]}"
retcode=$?

echo "$logname"
strace-treeify "$logname"

exit $retcode
