#!/bin/bash -

strace_log=$1

ancestry_data=$(mktemp)
pid_payloads=$(mktemp)

grep 'execve(' "$strace_log" |
  sed -e 's;\].*$;;g' |
    command-reparse.py  |
      sed -e 's/execve/execve /' |
        awk '{print $1 " " $3}' > "$pid_payloads"
        #awk '{$4=""; $2=""; print $0}' > "$pid_payloads"

sed -n -e 's;\([0-9]\+\).*signo=SIGCHLD.*si_pid=\([0-9]\+\).*;\1 \2;p' \
  "$strace_log" > "$ancestry_data"

strace-treeify-1.py "$ancestry_data" "$pid_payloads"

rm "$ancestry_data"
rm "$pid_payloads"
